### ISSUE TITLE
require's list in the emacs-lisp files

### ISSUE THREAD

**Issue by kostafey** [alexott/ecb#10]
The require's list of the emacs-lisp files is not shown in Ecb methods window.

The versions are:
* Ecb from 06.04.2013 (simply installed via ELPA)
* Cedet 2.0 (built-in).
* Emacs 24.3.1

I've mentioned about this problem (but with some other versions of ecb, cedet, emacs):
http://alexott.blogspot.com/2012/06/ecb-fresh-emacscedet.html?showComment=1340957563650#c1328574041536562069

The last time the porblem was solved by recompilation of Ecb with the latest cedet snapshot. I have trobles with using cedet-snapshot all the time becouse built-in cedet tries to load first and conflicts with it's snapshot in incomprehensible random cases.
So, I'm going to use built-in version.

It seems, that require's list is not appear in the Ecb through built-in cedet fault.
Therefore the questions are:

1. How can I determine the problem is really in the built-in cedet (to create correct bug-report)?

2. Probably, there is some cedet extensions are missing in the built-in version?

**Comment by alexott** [comment]
Please, report this error to https://github.com/ecb-home/ecb - now this is primary location for ECB development
