### ISSUE TITLE
ecb-new-cedet >>crashes<<

### ISSUE THREAD

**Issue by tomluchowski** [alexott/ecb#11]
Dear Sir, 
After installing your ecb-new-cedet emacs bundle against CEDET 1.1 I keep getting errors after ecb-activate,  Emacs version 24.2.1
Here';s the Message buffer : 

Loading /home/tom/cedet-1.1/common/cedet.el (source)...
Setting up CEDET packages...done
Loading /home/tom/cedet-1.1/common/cedet.el (source)...done [3 times]
ECB 2.40 uses CEDET 1.1 (contains semantic 2.1, eieio 1.4, speedbar 1.0.4).
ad-handle-definition: `split-window' got redefined
ad-handle-definition: `delete-other-windows' got redefined
ad-handle-definition: `delete-window' got redefined
Loading cc-mode...done
Loading semanticdb-file...done
Loading vc-git...done
.emacs has auto save data; consider M-x recover-this-file
semantic: connot find source file cl
Loading cogre-dot-mode...done
CameraManager.h has auto save data; consider M-x recover-this-file
Note: file is write protected [2 times]
DirectionalTrap.cpp has auto save data; consider M-x recover-this-file
Loading nxml-mode...done
Using vacuous schema
Note: file is write protected [3 times]
Wrote /home/tom/.emacs.desktop.lock
Desktop: 202 buffers restored.
For information about GNU Emacs and the GNU system, type C-h C-a. [5 times]
Class Declaration: class <name>[:parents] { ... };
Making completion list...
All requirements for ECB 2.40 fulfilled - Enjoy it!
The ECB is now deactivated.
ecb-clean-up-after-activation-failure: ECB 2.40: Errors during the layout setup of ECB. (error-type: error, error-data: ("Variable binding depth exceeds max-specpdl-size"))
Class Declaration: class <name>[:parents] { ... };

//********************************************************************************
My emacs file : 
//********************************************************************************
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; File name: ` ~/.emacs '
;;; ---------------------
;;;
;;; If you need your own personal ~/.emacs
;;; please make a copy of this file
;;; an placein your changes and/or extension.
;;;
;;; Copyright (c) 1997-2002 SuSE Gmbh Nuernberg, Germany.
;;;
;;; Author: Werner Fink, <feedback@suse.de> 1997,98,99,2002
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;
;;; Test of Emacs derivates
;;; -----------------------
(if (string-match "XEmacs\\|Lucid" emacs-version)
  ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
  ;;; XEmacs
  ;;; ------
  ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
    (progn
      (if (file-readable-p "~/.xemacs/init.el")
	  (load "~/.xemacs/init.el" nil t))
      )
  ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
  ;;; GNU-Emacs
  ;;; ---------
  ;;; load ~/.gnu-emacs or, if not exists /etc/skel/.gnu-emacs
  ;;; For a description and the settings see /etc/skel/.gnu-emacs
  ;;;   ... for your private ~/.gnu-emacs your are on your one.
  ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
  (if (file-readable-p "~/.gnu-emacs")
      (load "~/.gnu-emacs" nil t)
    (if (file-readable-p "/etc/skel/.gnu-emacs")
	(load "/etc/skel/.gnu-emacs" nil t)))

  ;; Custom Settings
  ;; ===============
  ;; To avoid any trouble with the customization system of GNU emacs
  ;; we set the default file ~/.gnu-emacs-custom

  ;;
 (c-add-style "microsoft"
              '("stroustrup"
                (c-offsets-alist
                 (innamespace . -)
                 (inline-open . 0)
                 (inher-cont . c-lineup-multi-inher)
                 (arglist-cont-nonempty . +)
                 (template-args-cont . +))))
 (setq c-default-style "ellemtel")

  (setq x-select-enable-clipboard t)
  (setq c-default-style "whitesmith"
	c-basic-offset 4)

  ;;FULL AKC
  (add-to-list 'load-path "~/.emacs.d/full-ack.el")
  (autoload 'ack-same "full-ack.el" nil t)
  (autoload 'ack "full-ack.el" nil t)
  (autoload 'ack-find-same-file "full-ack.el" nil t)
  (autoload 'ack-find-file "full-ack.el" nil t)

  ;;DESKTOP
  (desktop-save-mode 1)
  (setq history-length 250)
  (add-to-list 'desktop-globals-to-save 'file-name-history)

  ;;CEDET
  (load-file "~/cedet-1.1/common/cedet.el")
  (global-ede-mode 1)                      ; Enable the Project management system
  (semantic-load-enable-excessive-code-helpers)
  (global-srecode-minor-mode 1)            ; Enable template insertion menu
  (defun my-semantic-hook ()
  (semantic-add-system-include "/usr/include/OGRE/" 'c-mode)
  (semantic-add-system-include "/usr/include/OGRE/" 'c++-mode))
  (add-hook 'semantic-init-hooks 'my-semantic-hook)

  ;;ECB

  (add-to-list 'load-path
	       "~/.emacs.d/ecb-new-cedet")
  (require 'ecb)

;;;
  )
;;;
(speedbar 1)
(put 'downcase-region 'disabled nil)
(put 'upcase-region 'disabled nil)
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(column-number-mode t)
 '(delete-selection-mode nil)
 '(ecb-options-version "2.40")
 '(mark-even-if-inactive t)
 '(max-lisp-eval-depth 6000)
 '(max-specpdl-size 30800)
 '(mouse-drag-copy-region nil)
 '(scroll-bar-mode (quote right))
 '(show-paren-mode t)
 '(transient-mark-mode 1))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(default ((t (:inherit nil :stipple nil :background "white" :foreground "black" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 111 :width normal :foundry "unknown" :family "DejaVu Sans")))))

**Comment by alexott** [comment]
Please, report this error to https://github.com/ecb-home/ecb - now this is primary location for ECB development
