### ISSUE TITLE
ecb vc Git backend does not honor .gitignore

### ISSUE THREAD

**Issue by phaebz** [alexott/ecb#13]
With a directory under version control using Git, some files inside the directory files window show question mark icons  - although these files have been .gitignore'd

A manual `M-x vc-dir` correctly omits the ignored files. A manual `M-x ecb-vc-recompute-state` or via context menu does not work.

Is there a misconception on my side? Any hints?

**Comment by johnbendi** [comment]
What's going to happen now that there's no longer a function `vc-recompute-state`?

**Comment by alexott** [comment]
I don't know. Some active development now happens at https://github.com/ecb-home/ecb, so please, recreate this issue there...

**Comment by johnbendi** [comment]
On what branch does the active development take place? Cos what I can see there are years old update on master branch.

**Comment by alexott** [comment]
Hmmm, strange - I've seen commits there. Just open issue & current maintainer will contact you.  I don't expect that this will be major issue
