### ISSUE TITLE
Errors during the layout setup of ECB

### ISSUE THREAD

**Issue by m0smith** [alexott/ecb#17]
ecb-activate results in :

All requirements for ECB 2.40 fulfilled - Enjoy it! [2 times]
The ECB is now deactivated.
ecb-clean-up-after-activation-failure: ECB 2.40: Errors during the layout setup of ECB.  
    (error-type: void-variable, error-data: (ecb-examples-bufferinfo-buffer-name))

See http://stackoverflow.com/questions/20129637/emacs-24-3-1-cedet-2-0-built-in-and-ecb-20131116-1319-errors-during-the-layou

**Comment by alexott** [comment]
Please, report this error to https://github.com/ecb-home/ecb - now this is primary location for ECB development
