### ISSUE TITLE
ecb not activated on emacsclient

### ISSUE THREAD

**Issue by marcinant** [alexott/ecb#2]
When activating ECB from init.el it activates properly on Emacs, but on Emacsclient it's invisible.
ecb-toggle-ecb-windows doesn't work at all.

Even though ECB is activated - windows are hidden.

(require 'ecb)
Works on Emacs, broken on Emacsclient.

(require 'ecb-autoloads)
Works on both Emacs and Emacsclient - but requires manual activation.

ECB -> from new-cedet branch
Emacs version 24.2.50.2

**Comment by alexott** [comment]
Please, report this error to https://github.com/ecb-home/ecb - now this is primary location for ECB development
