### ISSUE TITLE
Merge from ware/ecb brings in completely broken commit

### ISSUE THREAD

**Issue by rmgrimm** [alexott/ecb#20]
Commit 66a3b856d4a175b14ec61b3492e465b0f08e5926 completely breaks any configuration that makes use of ```display-buffer-alist```.

I can understand the intent to bring ECB up-to-date, but it doesn't appear that there is any recent effort on making this actually work.

Can you reverse merge this commit so that it will at least stay out of the way?

Thanks!

**Comment by alexott** [comment]
Please, report this error to https://github.com/ecb-home/ecb - now this is primary location for ECB development
