### ISSUE TITLE
ecb cause the other component open new frame 

### ISSUE THREAD

**Issue by sunlin7** [alexott/ecb#21]
Dear Alexott:
    The ecb on emacs24.3.50.1 (emacs-snapshot from git) will cause other component open new frame. eg: after ecb-active, execute "man" -> "strlen" from mimbuffer, then emacs will popup a new frame to show the result. This also happen on org-mode for "org-open-at-point". The issue disappeared when desactive or hide ecb window.
    This issue didn't happen on emacs24.3 (current release version).
    Please give some hints for me to fix this issue.

Best regards
Sunline

**Comment by kimim** [comment]
I got the same problem. for example click on grep result will open new frame for the content.
I found that pop-to-buffer advised in ecb-layout.el probably is the root cause.

**Comment by alexott** [comment]
Please, report this error to https://github.com/ecb-home/ecb - now this is primary location for ECB development

**Comment by sunlin7** [comment]
OK, got it, thank you.
