### ISSUE TITLE
Cannot activate ECB: "Variable binding depth exceeds max-specpdl-size"

### ISSUE THREAD

**Issue by xaverm** [alexott/ecb#22]
Having installed ecb-20140215.114 from melpa/elpa for GNU Emacs 24.3.1 I cannot activate ecb without failure:

M-x ecb-activate

in the command buffer will not start ecb but produces:

The ECB is now deactivated.
ecb-clean-up-after-activation-failure: ECB 2.40: Errors during the layout setup of ECB. (error-type: error, error-data: ("Variable binding depth exceeds max-specpdl-size"))

in the *Messages* buffer. Increasing max-specpdl-size to some very large number, like 5000 does not help. I also noticed other strange things once I

(require 'ecb) 

in .emacs/init.el.
Eg.: C-x 3 to split the buffer vertically does not split the buffer vertically anymore and produces additional errs:
 
ad-Orig-split-window: Variable binding depth exceeds max-specpdl-size

in  the *Messages* buffer.
Any help to get ECB working would be most appreciated. Thanks.

XaverM

**Comment by alexott** [comment]
Please, report this error to https://github.com/ecb-home/ecb - now this is primary location for ECB development

**Comment by alexott** [comment]
Sean Chen found the workaround for it by using following snippet:

    (if (not (require 'uniquify nil t))
        (message "[warn] feature 'uniquify' not found!")
      (setq uniquify-buffer-name-style 'forward))
