### ISSUE TITLE
Disable ECB advices if ECB is deactivated

### ISSUE THREAD

**Issue by localredhead** [alexott/ecb#23]
http://stackoverflow.com/questions/9389679/how-to-unload-a-mode-e-g-unload-ecb-to-restore-winner-el-functionality  SO story for reference.

This is the fix:
````(add-hook 'ecb-deactivate-hook 
      '(lambda ()
         (ecb-disable-advices 'ecb-winman-not-supported-function-advices t)))````

With this in place I can call ````ecb-deactivate```` and still use ````winner-mode````

**Comment by alexott** [comment]
Please, report this error to https://github.com/ecb-home/ecb - now this is primary location for ECB development
