### ISSUE TITLE
ecb-autoloads doesn't compile under Emacs 24.4

### ISSUE THREAD

**Issue by manphiz** [alexott/ecb#26]
Using ecb 20140215.114 from MELPA. When using Emacs 24.4, trying to `(require 'ecb-autoloads)` fails with the following errors:
```
Warning (initialization): An error occurred while loading `/path/to/init.el':

error: Required feature `ecb-autoloads' was not provided.
```
Turns out ecb-autoloads.el doesn't get compiled during installing. Trying to compile it manually doesn't work either.

FTR, `ad-advised-definition-p' has been removed since Emacs 24.4, which could be related.

**Comment by alexott** [comment]
Please, report this error to https://github.com/ecb-home/ecb - now this is primary location for ECB development
