### ISSUE TITLE
GNU Emacs-24.4.1 win7 and ECB 2.40 Error: ECB can only be used with cedet [1.0pre6, 1.0.9]‏‏

### ISSUE THREAD

**Issue by JayForest** [alexott/ecb#29]
error: ECB 2.40 - Error: ECB can only be used with 
cedet [1.0pre6, 1.0.9]! Please install it and restart Emacs!
I tried a couple of things but have not figured out what exactly caused this issue.
I check my emacs I get the messages:CEDET Version: 2.0, 
I try to set the line:
　(defconst ecb-cedet-required-version-max '(1 0 4 9)
And replace the first '1' to a '2':

(defconst ecb-cedet-required-version-max '(2 0 4 9)
but it still cannot work well.

**Comment by alexott** [comment]
Please, use the https://github.com/ecb-home/ecb - this is now official repository...

**Comment by JayForest** [comment]
Thank you very much, now it can work well! I just use the emcacs + ESS +R , Whether can I use your configure or not,? 
Date: Sat, 7 Feb 2015 01:33:23 -0800

**Comment by alexott** [comment]
You can take my configuration - no problem, although I don't have much for ECB & my CEDET configuration is for development version...
