### ISSUE TITLE
Several "obsolete variable" warnings on Emacs 24.5.1

### ISSUE THREAD

**Issue by vlatkoB** [alexott/ecb#30]
Hi,

When ECB is activated, Compile Log opens with several warnings:

    /usr/share/emacs/24.5/lisp/cus-edit.elc:Warning: `default-major-mode' is an
    obsolete variable (as of 23.2); use `major-mode' instead.
    /usr/share/emacs/24.5/lisp/cus-edit.elc:Warning: Use `with-current-buffer'
    rather than save-excursion+set-buffer
    Warning: `special-display-function' is an obsolete variable (as of 24.3); use
    `display-buffer-alist' instead.

The last one keeps occurring.

`default-major-mode` is in `ecb-method-browser.el`, `special-display-function` is in `ecb-layout.el` and `save-excursion+set-buffer` in several files.

Emacs is 24.5.1 on Arch

Best regards,
vlatko

**Comment by alexott** [comment]
Please, report this error to https://github.com/ecb-home/ecb - now this is primary location for ECB development
