### ISSUE TITLE
ECB advices for window management functions ignore Emacs Window Choices

### ISSUE THREAD

**Issue by trashofmasters** [alexott/ecb#31]
I am using ECB 2.40.1 and I understand that this package advices some functions such as `switch-to-buffer-other-window` so that they always make change just to the edit window.

In practice those advices don't seem to respect the [window choices](http://www.gnu.org/software/emacs/manual/html_node/emacs/Window-Choice.html#Window-Choice) dictated by Emacs configuration variables such as `pop-up-frames` or `ns-popup-frames`.

You can this with `emacs -Q` and the following bit of elisp:
```elisp
(require 'ecb)
(ecb-activate)
(switch-to-buffer-other-window "*Messages*") ;; will cause a new frame to be opened.
```

Note: I'm currently using Emacs 25 on a Mac, but I have experienced this bug also on Emacs 24 still on the Mac.

**Comment by alexott** [comment]
Primary development of ECB now happens on https://github.com/ecb-home/ecb - please file issue there.
