### ISSUE TITLE
find-file on a new file in a not (yet) existing directory raises a "make buffer read-only" dialog

### ISSUE THREAD

**Issue by aufflick** [alexott/ecb#35]
As per http://emacs.stackexchange.com/questions/13935/ecb-never-ask-to-make-buffer-read-only when you eg. `C-x C-f foo/bar` where the directory `foo` does not exist (as you would commonly do in emacs, followed by `M-x make-directory`, you get a prompt that says "File /tmp/new-foo/bar.txt is read-only on disk.  Make buffer read-only, too? (y or n) n" or even worse, in GUI context you get a popup dialog.

I've tried to grep and trace the code (I'm running HEAD from this git repo) and have not been able to work out what is triggering this. It seems to be after a slight delay so I'd guess it's hooked into the stealthy read only check, but even if I set the file list buffer read only check to never, this still happens.

Can you give me any pointers about where I should be looking to fix this?

Thanks,

Mark.

**Comment by aufflick** [comment]
Incidentally, I'm also interested in knowing where this hook is, because it's probably a good start for me to look into triggering an update to the files browser window after C-x C-s saving a new file within a source.

**Comment by alexott** [comment]
Please, file this issue to the https://github.com/ecb-home/ecb - primary development is there. I'll close this repo soon
